### ISSUE TITLE
Weekly Operations Report- Sections and Table of Contents

### ISSUE THREAD

**Issue by brotzmanmj** [Analyticsphere/metricsReportsRequests#131]
Create sections and table of contents for the Weekly Operations Report, similar to what we have for the biospecimen weekly report.

Here are Kelsey's suggestions, @kmazzilli and @robertsamm please give your thoughts and guidance:
I think up until Figure 6.9 (current report page 67 divides nicely, but from there I would think the remainder of the tables would need to be put elsewhere to fit this particular pattern. Happy to discuss or create a mock up.

Section 1 Recruitment Status and Verification: Table 1/Figure 1 through Table 9
Section 2 Baseline Activity Completion: Table 10-Table 33
Section 3 Data Destruction, Refusals, Withdrawal, and Deceased Participants: Figure 5 through Table 36
Section 4 Baseline Incentive Eligibility: Table 37- Figure 6.9

Then this is where it gets a bit messy, and is just one idea for how to arrange the rest:

Section (maybe after section 1 above to go with verification data) Demographics of Verified participants : Tables 59-64
(Possibly adding pre-consent opt outs to section 3): Tables 48-50
(Possibly added to section 1): Tables 42-47, and Table 66
(possibly added to section 2): Table 51-58b
Section 5 QOL: Tables 65, 67-70

**Comment by KELSEYDOWLING7** [comment]
@kmazzilli  @robertsamm  This is what that proposal described above look like. Please note there are two Tables 24 and 25. The first set is the current Table 24 and Table 25. The second set comes from the recently approved request #130  for two new tables.

[Testing-Operations-Report.pdf](https://github.com/Analyticsphere/metricsReportsRequests/files/14827298/Testing-Operations-Report.pdf)

**Comment by KELSEYDOWLING7** [comment]
@erincschwartz  Based on this week's report is this good to close?

**Comment by brotzmanmj** [comment]
@KELSEYDOWLING7 this one will be for @kmazzilli  and @robertsamm to review. Has this been implemented yet or it is awaiting feedback on the proposal above?

**Comment by KELSEYDOWLING7** [comment]
@brotzmanmj  My mistake! I confused this with the biospecimen report version of this issue. No, still waiting for feedback on the proposal

**Comment by robertsamm** [comment]
@KELSEYDOWLING7 Thanks for making these updates! And sorry for the delayed feedback. This looks good. A couple comments below.
-I would suggest making 'Demographic of Verified participants' it's own section instead of subset under section 1. so it would be section 2 and then 'baseline activity completion' would be section 3 and so on
-For the new tables 24 and 25 'Completion of Baseline Survey (Modules 1-4) by Collection Setting, among Participants who Donated Baseline Samples'. Can you please update the title to note this is among 'verified' participants. And then the total label should say 'Total Verified Participants'. This is to better match the format of the other metrics in this report.
-Table 51-53, suggest moving to 'Recruitment Status and Verification' section between table 6 and 7a
-table 54-58b suggest making it's own section 'Time to Completion for Enrollment'. Maybe after 'Recruitment Status and Verification' but before 'Demographic Data'? 
-I suggest changing section 5 title from '3 Month Quality of Life' to 'Follow Up Activity Completion' to make this more future proof if we add any addtl metrics here in the future besides just the QOL survey

Let me know if you have any questions! Before you relabel table numbers, do you want to just move them around to the places suggested above and I'll review again just to make sure the order still makes sense and then you can renumber them.

**Comment by KELSEYDOWLING7** [comment]
@robertsamm  No problem! Thanks for the notes. Please let me know how this looks

[Testing-Operations-Report.pdf](https://github.com/Analyticsphere/metricsReportsRequests/files/14948293/Testing-Operations-Report.pdf)

**Comment by robertsamm** [comment]
Good morning @KELSEYDOWLING7 , here are the last revisions to the Operations Report draft that consolidates feedback from Michelle, Kaitlyn, and myself. In addition to the edits listed below, I also proposed changes to the summary in the 'general information' section below - can you please review and let me know if the revised summary looks good to you? I left one question for you on when the data for the report is pulled. 

**Edit requests to report:**
1. Minor changes to section titles:
a. Section 1, please change to: 'Recruitment and Verification Status'
b. Section 3, please add an 's' to 'demographic' and capitalize the 'p' in participants - 'Demographics of Verified Participants'
2. Please move the section on data destructions/refusals/withdrawals below 'baseline incentive eligibility'. As it seems to make more sense to have the incentive stuff come after baseline activity completion metrics. (section 4 baseline activities, section 5 incentives, section 6 destruction, section 7 follow up activities)
3. Please move pre-consent opt outs (tables 48-50) from the section on withdrawals, data destruction, etc to the end of Section 1. 
5. Figure 5.10-5.12, can we swap the colors so that the 'Withdrawals per 1K Consented Participants'=light blue and 'Data Destruction per 1K Consented Participants'=yellow? That way the yellow/oranges go with destruction and the blues go with withdraws?
6. Table 66 (currently at the end of Section 1) on uninvited participants - to be removed from Operations report as in QC
7. Renumber the tables and figures within each section, throughout the report. They should be 1-1, 1-2, 1-3, etc.
8. Pgs 45-46 seem to have something funky going on with spacing in the table title and the extra pages. Please fix.
9. There are a few figures and tables where the titles are getting cut off the page because of the font size and bolding. Could you please page through to identify them and adjust in the final report?

**General Information Section - Revised:**
This Weekly Operations report contains tables and plots on Connect recruitment and study activity completion. This includes metrics on enrollment from invitation through verification, recruitment success, demographic data of verified participants using the de-identified demographic data, incentive eligibility, and data on opt-outs and refusals and withdrawals. High level study activity completion metrics is also included in this report for baseline activities and some follow up activities. For more detailed metrics on baseline biospecimen collections and the biospecimen survey, please see the Weekly Biospecimen Report. For more detailed metrics on survey completion, please see the Weekly Survey Report. 
 
The analytic data set for this report is created from the “nih-nci-dceg-connect-prod-6d04.FlatConnect.participants_JP” table in BQ which is updated daily. All variables are stored as CIDs which can be found in the master dictionary: https://episphere.github.io/ conceptGithubActions/aggregate.json.
 
The Operations report is run on a weekly basis and encompasses data through 8am the day the report is run _[Kelsey please confirm this is accurate/revise]_. Records with the following statuses are excluded from this report: (1) recruit type=not active and/or (2) recruit type=active and verification status=duplicate. Atypical records under investigation are not included in the metrics tables and may result in Total columns that do not add up to 100. This report contains data as of DD Month, YYYY.

**Comment by KELSEYDOWLING7** [comment]
Thanks @robertsamm  please let me know if I missed anything.
[Testing-Operations-Report.pdf](https://github.com/Analyticsphere/metricsReportsRequests/files/15278865/Testing-Operations-Report.pdf)

As a side note for all reports, as the months continue the time trend plot's x axis ticks (dates) are going to get harder and harder to read. We may need to switch from every 2nd week marked to every 4th week marked for legibility.

**Comment by robertsamm** [comment]
Hi @KELSEYDOWLING7 thanks for making these updates so quickly! The only final comment I have is there seems to be some issues with spacing. Can you take a look through the report one more time to see of any of the large gaps can be fixed?

For your comment about the time trend plot's, I agree. @brotzmanmj any concerns about switching the weeks marked in the x axis? We could just mark the first week of each month? (See figure 1.5 as an example below)
![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/67074735/94c88e1f-9844-465e-9eb1-ce1178d38869)

**Comment by brotzmanmj** [comment]
I agree, marking just the first week of the month makes sense at this point. It would still contain all the data points?

**Comment by robertsamm** [comment]
Yes, it should still contain all the data points.
@KELSEYDOWLING7 For figure 1.4 with the overall counts. I think the Y-axis should be updated too as they are also looking crowded. On the left could have the counts only marked every 200 and the right every 2,000? (but still have the tickmarks for every 100/1,000). See below.

![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/67074735/31f2ed3a-8d83-4fe7-ba0d-06dc7e9d56df)

**Comment by KELSEYDOWLING7** [comment]
@robertsamm  No problem! Because these time plots and counts are based on certain days of the week I would not be able to set the x axis to the first of the month, but I can do a set number of weeks, for example 4 weeks instead if the 2 weeks we have now. Please let me know what you think. (See example below)
![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/0ab7d106-1ec9-4687-a93e-c6b36ada7d1a)


Also unfortunately I can't do much about the award spacing. When I remove the code line that is causing that large gap, the first table of the section floats above the head. (See example below)
![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/797837f7-00f5-4017-9011-77c130fb9f04)

**Comment by robertsamm** [comment]
Hi @KELSEYDOWLING7 That's ok for the gaps - I see what you mean! And I think the x-axis with the date every 4 weeks looks good as shown. I think you are good to finalize the code for this and get it into the automation when it's next due for updates. 

In the meantime, would you be able to run the report ad hoc one more time with the latest changes using this week's data? Michelle, Kaitlyn, and I are meeting on Friday to review the Operations report (more to note any trends, concerns we want to bring up to sites, etc rather than data issues) and it would be nice to have this updated report for our review!

**Comment by KELSEYDOWLING7** [comment]
@robertsamm  Great! Please see attached 
[Testing-Operations-Report.pdf](https://github.com/Analyticsphere/metricsReportsRequests/files/15324859/Testing-Operations-Report.pdf)

**Comment by robertsamm** [comment]
Thanks @KELSEYDOWLING7, looks good!
