### ISSUE TITLE
Duplicates Report Updates

### ISSUE THREAD

**Issue by robertsamm** [Analyticsphere/metricsReportsRequests#15]
Jing, please wait to address these comments after you finish your work on updating the Rct and Biospec Reports. 

For the [Duplicates Report](https://nih.app.box.com/file/1117109700996),
1. Please take out the filter on active duplicates. All duplicates should be included in the report. Madhuri said she was just pulling the data from the participants table (with no filters applied).
2. In the first table, please change the percentages to be a column percent not a row percent.
3. Please add an additional graph that shows the time trend for participants already enrolled but reflected as a proportion of the total number of invitations at those time points. Total # of invitations=total number of active recruits at those time points.
4. If possible, please add a marker for both time trends on 12/8 that shows when the new login screen pathways were pushed to prod. If the marker isn't possible or easy to add, then a footnote will work instead.

**Comment by jeannewu** [comment]
Hi, Amelia,

Can I put the duplicate report in the regular weekly report in one pdf file together?

Just check.

Thanks a lot.

Best, Jing

From: Amelia Roberts ***@***.***>
Date: Thursday, January 26, 2023 at 9:46 AM
To: Analyticsphere/metricsReportsRequests ***@***.***>
Cc: Wu, Jing (NIH/NCI) [C] ***@***.***>, Assign ***@***.***>
Subject: [EXTERNAL] [Analyticsphere/metricsReportsRequests] Duplicates Report Updates (Issue #15)

Jing, please wait to address these comments after you finish your work on updating the Rct and Biospec Reports.

For the Duplicates Report<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fnih.app.box.com%2Ffile%2F1117109700996&data=05%7C01%7Cjing.wu2%40nih.gov%7C123be8c92aff43bca4dd08daffac1890%7C14b77578977342d58507251ca2dc2b06%7C0%7C0%7C638103411855230341%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=OKgntuDKvhCPGnm9TsHbj5XEBbj0CDzgRY42HGAIUEw%3D&reserved=0>,

  1.  Please take out the filter on active duplicates. All duplicates should be included in the report. Madhuri said she was just pulling the data from the participants table (with no filters applied).
  2.  In the first table, please change the percentages to be a column percent not a row percent.
  3.  Please add an additional graph that shows the time trend for participants already enrolled but reflected as a proportion of the total number of invitations at those time points. Total # of invitations=total number of active recruits at those time points.
  4.  If possible, please add a marker for both time trends on 12/8 that shows when the new login screen pathways were pushed to prod. If the marker isn't possible or easy to add, then a footnote will work instead.

—
Reply to this email directly, view it on GitHub<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FAnalyticsphere%2FmetricsReportsRequests%2Fissues%2F15&data=05%7C01%7Cjing.wu2%40nih.gov%7C123be8c92aff43bca4dd08daffac1890%7C14b77578977342d58507251ca2dc2b06%7C0%7C0%7C638103411855386554%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=HD88B3ePdPDni7tbRt64o9X9uYGRhk5wcSul7Giddpg%3D&reserved=0>, or unsubscribe<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAXZVEF4J32DLJCQYIVHCRQ3WUKE33ANCNFSM6AAAAAAUHSUTAI&data=05%7C01%7Cjing.wu2%40nih.gov%7C123be8c92aff43bca4dd08daffac1890%7C14b77578977342d58507251ca2dc2b06%7C0%7C0%7C638103411855386554%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=0vfFBrH5m8fWop0975I6aLQ74g8w%2B5t9gKRmKwwa7kY%3D&reserved=0>.
You are receiving this because you were assigned.Message ID: ***@***.***>
CAUTION: This email originated from outside of the organization. Do not click links or open attachments unless you recognize the sender and are confident the content is safe.

**Comment by robertsamm** [comment]
No, they'll need to remain separate. The regular weekly recruitment report filters out active duplicates. We don't want any duplicates filtered out of the duplicate report.

**Comment by jeannewu** [comment]
@robertsamm I have just put the duplicate report in the folder. Please check it ( I used today's data)

**Comment by robertsamm** [comment]
Hi Jing, it looks like this still needs some work but the recruitment and biospecimen reports take priority. Please work on those first before turning your attention to this. You can check with @FrogGirl1123 for priorities

**Comment by jeannewu** [comment]
Got it. Thanks.

From: Amelia Roberts ***@***.***>
Date: Thursday, January 26, 2023 at 1:58 PM
To: Analyticsphere/metricsReportsRequests ***@***.***>
Cc: Wu, Jing (NIH/NCI) [C] ***@***.***>, Mention ***@***.***>
Subject: [EXTERNAL] Re: [Analyticsphere/metricsReportsRequests] Duplicates Report Updates (Issue #15)

Hi Jing, it looks like this still needs some work but the recruitment and biospecimen reports take priority. Please work on those first before turning your attention to this. You can check with @FrogGirl1123<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FFrogGirl1123&data=05%7C01%7Cjing.wu2%40nih.gov%7C4dc9652242774c35b49108daffcf5d55%7C14b77578977342d58507251ca2dc2b06%7C0%7C0%7C638103563328926596%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=HX5ac80umbwFh4l%2FGnK32qN7dvSNEcg0uwc3NnsItkg%3D&reserved=0> for priorities

—
Reply to this email directly, view it on GitHub<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FAnalyticsphere%2FmetricsReportsRequests%2Fissues%2F15%23issuecomment-1405460659&data=05%7C01%7Cjing.wu2%40nih.gov%7C4dc9652242774c35b49108daffcf5d55%7C14b77578977342d58507251ca2dc2b06%7C0%7C0%7C638103563328926596%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=KQMk2I8AF2W8DQo6IOil2W9mR%2By%2BYBQJlitFP9lbIaA%3D&reserved=0>, or unsubscribe<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAXZVEF66XVF4GTEI546NFYLWULCM3ANCNFSM6AAAAAAUHSUTAI&data=05%7C01%7Cjing.wu2%40nih.gov%7C4dc9652242774c35b49108daffcf5d55%7C14b77578977342d58507251ca2dc2b06%7C0%7C0%7C638103563329082780%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=3htUok%2FH7qnPa7bdZNEjLpQTniVhHetaMZzZk4OcOmw%3D&reserved=0>.
You are receiving this because you were mentioned.Message ID: ***@***.***>
CAUTION: This email originated from outside of the organization. Do not click links or open attachments unless you recognize the sender and are confident the content is safe.

**Comment by jeannewu** [comment]
@robertsamm this duplicate report is updated with the request as Michelle reviewed

**Comment by KELSEYDOWLING7** [comment]
@robertsamm  This report will be added to the monthly automation, starting 6/1. Is this issue ok to close?

**Comment by robertsamm** [comment]
Hi @KELSEYDOWLING7 we would like to request some additional changes to the duplicates report but this issue is so old I think it best to close out and start a new issue. I'll get a new issue started!
