### ISSUE TITLE
Bio Weekly - Adjust x-axis on Weekly Collections Figures

### ISSUE THREAD

**Issue by HopkinsDC** [Analyticsphere/metricsReportsRequests#59]
Please adjust the x-axis of all figures to show completed weeks only. The figures should only include data points for completed weeks (Monday through Sunday). For example, the plots in the biospecimen metrics report generated on Monday, 9/11/2023, should have an x-axis in which the last date is the previous Monday, 9/5/2023. 

**Requestor(s):** Michelle

**Table or Figure Title:** All figures with a weekly date x-axis

**Metrics to be updated or created:** Update existing figures

**Variables needed (include variable name and Concept ID):** N/A

**Specify numerator and denominator by variable name where applicable:** N/A

**Mock-up table if applicable:** N/A

**Approved by:** Domonique

**Comment by brotzmanmj** [comment]
@KELSEYDOWLING7  please also check all of the weekly collection figures against the number of samples collections per week in the Weekly Logs (https://nih.app.box.com/folder/200244295811). Some of the figures, such as the one for HFH, show a downward trend that is not evident in the weekly totals.

**Comment by KELSEYDOWLING7** [comment]
Finally got back into Github!!!

@HopkinsDC  I am able to set the limit of the last point on the x-axis to the previous full week (for example, this week's should end on 9/11), but unfortunately no matter what I code there is an additional week showing afterwards on the axis but with no point. I think its similar to the y axis with 100 being the limit but the axis going slightly over. I also noticed that all three locations have different start dates for first specimen collection so I had them all start at 6/20/22 for consistency. Let me know if that needs to be changed


@brotzmanmj Figure 4.1 for HFH looks at those in HFH with any completed specimen donation (blood or urine or mouthwash), and then of those participants, those that have completed the BUM survey (and have both a start and submit time) and have checked in. That is the denominator. 
Then graphs the proportion of those participants with submit times under 3 hours of check-in (numerator) out of all participants of this group. Please let me know if any of that logic has to be changed. 

I do see the ‘Specimens Collection per Week’ column, but I’m not sure that’s a helpful comparison since that does not reflect the time of the survey completion, only that those participants have a check in time. To me it just seems like a good reference point for the n (participants checked in per week). But I also don’t know if that column has the same filters (BUM survey start and completion time for example), in which case I would not be able to use it as a comparison. 


I tweaked the code slightly so that the Site filter is pushed to the beginning of each figure code as opposed to the middle. It did change the plots slightly. Please let me know if you believe these look more accurate (compared to the last report).

![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/101d2a70-dae3-4da4-bf16-611c223198b4)

![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/0ed4be78-e853-40ea-90d6-4e57e8985b87)

![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/67b4d335-407f-4e8f-ac1c-02b37e78fc96)

**Comment by HopkinsDC** [comment]
@KELSEYDOWLING7 Thanks, Kelsey. I think having the extra week is fine if there is no data point, so the graphs are good to go in that respect. **Please apply this to all graphs in the biospecimen metrics report**.

I will let Michelle follow up with your response to her comment.

**Comment by KELSEYDOWLING7** [comment]
@HopkinsDC  With Jing's help I was able to change my code slightly to make the date cut off as requested

![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/05489c12-3246-4f1c-8de1-74e284e0b6c6)

**Comment by KELSEYDOWLING7** [comment]
@HopkinsDC  With Jing's help I was able to change my code slightly to make the date cut off as requested

![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/05489c12-3246-4f1c-8de1-74e284e0b6c6)

**Comment by brotzmanmj** [comment]
@KELSEYDOWLING7 sorry I was communicating outside of the github issue. I have re-opened it and put it back in the To Do column. Per our discussion on email, please update Figures 6 through 15 on the Biospecimen Weekly Metrics Report to include weekly collection counts through the latest 'complete' week corresponding to the weekly log, and keep just the biweekly labels on the x axis.

**Comment by KELSEYDOWLING7** [comment]
@brotzmanmj  Please let me know if this is readable or if you need more labels on the x-axis

![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/7c6ac8a7-cb6f-458d-9b3d-85240fb6687b)

**Comment by brotzmanmj** [comment]
Hi @KELSEYDOWLING7  I compared it to the one in the current weekly report and it looks exactly the same to me?

**Comment by KELSEYDOWLING7** [comment]
@brotzmanmj  Oh I'm sorry, you're right.  So the data already goes to 10/16(week of 10/16-20/22). Do you want me to add extra unmarked x ticks for the in between weeks so it's easier to see? For example, after 10/9/23 there would be a blank tick representing 10/16

**Comment by brotzmanmj** [comment]
@KELSEYDOWLING7  let's discuss when we meet at 4:30 about the notifications if we can stay on a few extra minutes.

**Comment by HopkinsDC** [comment]
@KELSEYDOWLING7 @brotzmanmj Has this issue been resolved?

**Comment by KELSEYDOWLING7** [comment]
@HopkinsDC  Not yet but I can work on this more today to try and get it closed asap

**Comment by KELSEYDOWLING7** [comment]
@HopkinsDC  Or rather, the issue with adding the last full week's data to the end of the plot, even if that is an in between week and not labeled on the x axis, has been resolved.

The other issue that was brought up on Friday is that Figures 6-15 don't match the weekly logs from the Operations Reports. Me and Jing are working on that issue now

**Comment by HopkinsDC** [comment]
@KELSEYDOWLING7 Okay, thanks. I'm going to create a separate issue for the latter issue (Figures 6-15/weekly reports discrepancy) since the former issue (x-axis adjustments) is complete. Let me know if you have any concerns about this.

For the 10/30 metrics report, it looks like the x-axis adjustments have already been applied to the report automation, correct? (Just want to confirm with you before moving to "Done").

**Comment by KELSEYDOWLING7** [comment]
@HopkinsDC  Ok that sounds good. Yes, the x axis adjustments have already been implemented into the automation. The Figures 6-15 numbers issue may also be resolved today and put on the automated report for Monday but we'll have to see how testing goes. Or if you'd rather me put the new plots here to review first before putting them into the automated report
