### ISSUE TITLE
Wkly Biosp - Daily Avg # of shipments and # collections

### ISSUE THREAD

**Issue by robertsamm** [Analyticsphere/metricsReportsRequests#7]
For the biospecimen weekly report, please add a table that shows the average daily number of shipments (boxes) coming from each site and the daily number of collections from each site. This should be stratified by site and show the overall total.

@HopkinsDC can you please add a comment to this issue that indicates how exactly you want this table to look like, title of table, etc?

**Comment by jeannewu** [comment]
I've just seen your message. Sorry for my late response. I will add this table into the coming biospecimen metric this week. Please let me know if anything is needed in this table. Thanks a lot, Amelia and Dominique

**Comment by jeannewu** [comment]
May you please show me where in the box I can find more detailed requirements for this table if any. Thanks a lot.

**Comment by jeannewu** [comment]
Hi, Dominique, the biospecimen collections started in Jun. 13, 2022 till now (this is the 18th week). Marshfield(two sites) had shipped 128 boxes, HP had shipped 107 boxes, SF 52 boxes, UOC with 91 boxes, HFHS with 43 boxes till this 18th week. The boxes tables are counted by tubes in a box, and different numbers of tubes per box are different by shipments, by sites by collections at each time, and different start time between different site (UOC started late). In this 18th week, Marshfield had shipped 10 boxes, HP with 9 boxes, HFHS with 3 boxes, SF with 8 boxes and UOC with 6 boxes. And the tubes in each box are different, too. Will you mean to count the daily shipment by average numbers  of boxes in each week based on each week total boxes in the shipment by site regardless of the numbers of tubes in a box, right?

**Comment by HopkinsDC** [comment]
@jeannewu Jing, the graph for the number of boxes by site you sent via needs to be per day, not cumulative. Can you also add another line that shows the total boxes per day? (See mock-up below for example and title to use for the graph)
![Picture1](https://user-images.githubusercontent.com/85250133/196498769-26eb3e29-d7a8-40eb-a8c3-143605cb4467.png)

Additionally, second graph is needed for the number of visits per day by site; This is also by day, not cumulative, and should have a another line to show the total number of boxes pre day. (See mock-up below for example and title to use for the graph)
![Picture2](https://user-images.githubusercontent.com/85250133/196499187-5d15c2bc-5c45-4f1e-85f1-9f43812da58e.png)

**Comment by jeannewu** [comment]
Hi, Dominique,

Thank you very much for your prompt response.

Base on the biospecimen data, the range of the number of box collected by week by site is from 3-11 boxes (in the last week) by site. In this way, some site would have less than one box (3/7) collected per day by week, is this what you want to have in this plot by average box daily collection per week by site (shown below?
***@***.***

Thanks a lot.

Best, Jing
From: Domonique Hopkins ***@***.***>
Date: Tuesday, October 18, 2022 at 1:12 PM
To: Analyticsphere/metricsReportsRequests ***@***.***>
Cc: Wu, Jing (NIH/NCI) [C] ***@***.***>, Mention ***@***.***>
Subject: [EXTERNAL] Re: [Analyticsphere/metricsReportsRequests] Wkly Biosp - Daily Avg # of shipments and # collections (Issue #7)

@jeannewu<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fjeannewu&data=05%7C01%7Cjing.wu2%40nih.gov%7C186dda24aae54bd936db08dab12bde22%7C14b77578977342d58507251ca2dc2b06%7C0%7C0%7C638017099218126768%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=QvC2YWTecgH54dqFxQjh7qvQ6CXIWiqK0ZcpzmMgCnU%3D&reserved=0> Jing, the graph for the number of boxes by site you sent via needs to be per day, not cumulative. Can you also add another line that shows the total boxes per day? (See mock-up below for example and title to use for the graph)
[Picture1]<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F85250133%2F196498769-26eb3e29-d7a8-40eb-a8c3-143605cb4467.png&data=05%7C01%7Cjing.wu2%40nih.gov%7C186dda24aae54bd936db08dab12bde22%7C14b77578977342d58507251ca2dc2b06%7C0%7C0%7C638017099218126768%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=z7DlGCU03zLzMHIyI9sM68PMhTEk8kxxuaC2KtRb7A8%3D&reserved=0>

Additionally, second graph is needed for the number of visits per day by site; This is also by day, not cumulative, and should have a another line to show the total number of boxes pre day. (See mock-up below for example and title to use for the graph)
[Picture2]<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F85250133%2F196499187-5d15c2bc-5c45-4f1e-85f1-9f43812da58e.png&data=05%7C01%7Cjing.wu2%40nih.gov%7C186dda24aae54bd936db08dab12bde22%7C14b77578977342d58507251ca2dc2b06%7C0%7C0%7C638017099218126768%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=pl2zUIjrT60Yh9Eldw7yH24kgZgJLWMI%2B1bO%2Ff6o1xo%3D&reserved=0>

—
Reply to this email directly, view it on GitHub<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FAnalyticsphere%2FmetricsReportsRequests%2Fissues%2F7%23issuecomment-1282741976&data=05%7C01%7Cjing.wu2%40nih.gov%7C186dda24aae54bd936db08dab12bde22%7C14b77578977342d58507251ca2dc2b06%7C0%7C0%7C638017099218126768%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=5Ffo7zhFx2d2FBKIR5KRfC%2BDiCq1UubWOKY9EpmgIHU%3D&reserved=0>, or unsubscribe<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAXZVEFYX3EU7J5YNAKFSZN3WD3K53ANCNFSM6AAAAAAQ67USGI&data=05%7C01%7Cjing.wu2%40nih.gov%7C186dda24aae54bd936db08dab12bde22%7C14b77578977342d58507251ca2dc2b06%7C0%7C0%7C638017099218126768%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=bs7ZEFh28qQLRC%2BMIuqu7SR8EhMkbRb6O8PneyMvWK0%3D&reserved=0>.
You are receiving this because you were mentioned.Message ID: ***@***.***>
CAUTION: This email originated from outside of the organization. Do not click links or open attachments unless you recognize the sender and are confident the content is safe.

**Comment by jeannewu** [comment]
Hi, Dominique, thank you very much for sending this template plots. The x axis in this plot is from Oct1. to Oct. 18, seems the within two week range. So I guess you would like to check the daily shipment of each site in this current week by average cumulative number of boxes on each corresponding date during these two-week range, or one-week range? In this current 18th week, shipment date across all five sites were from Oct. 10, 2022~Oct. 14, 2022 defined by "BioShip_ShipTime_v1r0": MFH had shipped 11 boxes (Box 120-131), HP had shipped 9 boxes (Box 99-107), HFHS had shipped 3 boxes (Box 41-43), SF had shipped 8 boxes (Box 45-52) and UoC had shipped 6 boxes (Box85-91). So you would like to have the plot for the average box collections by day for the most recent week from Oct.10 to Oct 16, 2022?
