### ISSUE TITLE
Operations Report - fix errors in Figures 4.0-4.9

### ISSUE THREAD

**Issue by brotzmanmj** [Analyticsphere/metricsReportsRequests#74]
Figure 4.0 the date 10/16/2023 is included making all the curves go to 0 but that is not correct. We think it's because the code is pulling in the week that is past when the data are actually available.

Figures 4.1 through 4.9 the legend at the bottom is wrong so the curves are mislabeled. The correct legend is in Figure 4.0. And you'll see those curves go through 10/2/2023. All graphs 4.0 - 4.9 should go through the last complete week when data are available on the Monday-Sunday schedule we defined for the Weekly Logs.

**Comment by KELSEYDOWLING7** [comment]
@kmazzilli  @brotzmanmj  To clarify, is it alright that the plots are currently going to 10/2? The x-axis is biweekly, so this past full week (ending in 10/9) wouldn't show.


And the other plots have been fixed. For Figure 4.0, that is now ending with 10.2.
![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/4a32f7b2-f710-4290-a446-add11f46e70e)

The colors have been fixed for Figures 4.1-4.9, here is an example 
![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/fb49230b-0c58-430d-bb6a-b8d59b56fa4b)

**Comment by KELSEYDOWLING7** [comment]
@kmazzilli  Copying Jing's comment on issue #67  here for organizational/tracking purposes for this issue:

"as Michelle mentioned before all the weekly and cumulative data (as the weekly log ones) are listed as a cycle of "Monday-Sunday". So all the data on Monday would be reported in the next cycle not in this week's report. I mean the data on Monday (e.g. Oct. 16) which the report is done would not be reported in the weekly log or as well as not in the weekly or cumulative plots."

Next week's report will have 10/16 data

**Comment by kmazzilli** [comment]
@KELSEYDOWLING7 it's fine that it goes to 10/2 since the axis is biweekly. Thanks!

**Comment by robertsamm** [comment]
Hi @KELSEYDOWLING7 sorry, I know we just said 10/2 would be good but we weren't taking into consideration that we plan to present these time trends on the monthly site calls and need the most up to date data in order to discuss how the site did for the past month based on their data from the previous month.

Are you able to run all the operations report plots so that the latest complete week is always there? So for the 10/16 report, the data would be through 10/15 (week starting 10/9 and ending 10/15)?

**Comment by KELSEYDOWLING7** [comment]
@kmazzilli  So would you want these to switch to a weekly x-axis? Otherwise I don't believe that would be possible to have all the x axis be biweekly and then the last week or two be weekly to ensure the most recent week is on there.

If the weekly logs are set to end on Sunday, I don't think the report would recognize to end the plot with 10/16 since technically the last date of data would be the 15th

**Comment by KELSEYDOWLING7** [comment]
Fixed in #80
