### ISSUE TITLE
Bio Weekly - Incorporate Clinical Biospecimen Metrics into Weekly Metrics Report

### ISSUE THREAD

**Issue by HopkinsDC** [Analyticsphere/metricsReportsRequests#8]
Clinical metrics drafted and added to the latest metrics report from Jing (10/11) to better align with the current tables. Ready to go to Jing.

Clinical Metrics Draft: https://nih.app.box.com/file/1037513568428

**Comment by HopkinsDC** [comment]
Mock-ups mentioned in the Clinical Metrics Draft document: 
[Metrics clinical additioanal mock ups 10.13.22.docx](https://github.com/Analyticsphere/metricsReportsRequests/files/9811840/Metrics.clinical.additioanal.mock.ups.10.13.22.docx)

**Comment by jeannewu** [comment]
Hi, Dominique,

How about this graph on the box shipment by site by week?
***@***.***

From: Domonique Hopkins ***@***.***>
Date: Tuesday, October 18, 2022 at 11:03 AM
To: Analyticsphere/metricsReportsRequests ***@***.***>
Cc: Wu, Jing (NIH/NCI) [C] ***@***.***>, Assign ***@***.***>
Subject: [EXTERNAL] Re: [Analyticsphere/metricsReportsRequests] Bio Weekly - Incorporate Clinical Biospecimen Metrics into Weekly Metrics Report (Issue #8)

Assigned #8<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FAnalyticsphere%2FmetricsReportsRequests%2Fissues%2F8&data=05%7C01%7Cjing.wu2%40nih.gov%7C1b6b8878b8364243895708dab119eeb4%7C14b77578977342d58507251ca2dc2b06%7C0%7C0%7C638017022196516792%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=SnXtBA4jfzKOUpckUjWyQsCWM8RTkiPiO34JzTCzxNM%3D&reserved=0> to @jeannewu<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fjeannewu&data=05%7C01%7Cjing.wu2%40nih.gov%7C1b6b8878b8364243895708dab119eeb4%7C14b77578977342d58507251ca2dc2b06%7C0%7C0%7C638017022196516792%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=DpUreueLJr33Tntdym5SW8Onshb48taOADmK15nwl6w%3D&reserved=0>.

—
Reply to this email directly, view it on GitHub<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FAnalyticsphere%2FmetricsReportsRequests%2Fissues%2F8%23event-7612696016&data=05%7C01%7Cjing.wu2%40nih.gov%7C1b6b8878b8364243895708dab119eeb4%7C14b77578977342d58507251ca2dc2b06%7C0%7C0%7C638017022196516792%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=QO%2BVIrB2zCza%2FZs%2Fp2xX932Pg%2B8klBIPgw6jbXWyoIY%3D&reserved=0>, or unsubscribe<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAXZVEF7YQ4INWPAPX4AMVA3WD233XANCNFSM6AAAAAARCUWO3Q&data=05%7C01%7Cjing.wu2%40nih.gov%7C1b6b8878b8364243895708dab119eeb4%7C14b77578977342d58507251ca2dc2b06%7C0%7C0%7C638017022196516792%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=H0N97y8%2FAjWdqa9rnispdR0VrPOh5jC37jI53ZikcLo%3D&reserved=0>.
You are receiving this because you were assigned.Message ID: ***@***.***>
CAUTION: This email originated from outside of the organization. Do not click links or open attachments unless you recognize the sender and are confident the content is safe.

**Comment by StephanieWeinstein** [comment]
Hi @jeannewu ,
Please see above for comments that we had put on the biospecimen metrics reports. There are two documents here.  Can you take what you sent this morning and apply these to the metrics you sent this morning?
Thanks,
Stephanie

**Comment by jeannewu** [comment]
Hi, Stephanie,

thank you very much for directing me to this post in GitHub. Yes, since no valid recruitment table is available for the biospecimen part, all the tables in the biospecimen metrics report sent to you yesterday are done with only the biospecimen data from prod without linking to the recruitment table in the similar way I can try to mock up the tables shown in biospecimen_metrics_baseline_participants_CLINICAL MOCKUP.pdf (https://nih.app.box.com/file/1037513568428)). I will generate the tables in the guidance of the biospecimen mock-up file when all the data are available for the recruitment and biospecimen data later. Thanks a lot.

Best, Jing

From: Stephanie Weinstein ***@***.***>
Date: Monday, December 5, 2022 at 3:16 PM
To: Analyticsphere/metricsReportsRequests ***@***.***>
Cc: Wu, Jing (NIH/NCI) [C] ***@***.***>, Mention ***@***.***>
Subject: [EXTERNAL] Re: [Analyticsphere/metricsReportsRequests] Bio Weekly - Incorporate Clinical Biospecimen Metrics into Weekly Metrics Report (Issue #8)

Hi @jeannewu<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fjeannewu&data=05%7C01%7Cjing.wu2%40nih.gov%7C8872ab13cfb64bb4180808dad6fd9af9%7C14b77578977342d58507251ca2dc2b06%7C0%7C0%7C638058681963191909%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=rrg1Y%2BgF3smMuWTXHwWNDvFqV1AzTe%2FnpBhf%2FIaqgXE%3D&reserved=0> ,
Please see above for comments that we had put on the biospecimen metrics reports. There are two documents here. Can you take what you sent this morning and apply these to the metrics you sent this morning?
Thanks,
Stephanie

—
Reply to this email directly, view it on GitHub<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FAnalyticsphere%2FmetricsReportsRequests%2Fissues%2F8%23issuecomment-1338110756&data=05%7C01%7Cjing.wu2%40nih.gov%7C8872ab13cfb64bb4180808dad6fd9af9%7C14b77578977342d58507251ca2dc2b06%7C0%7C0%7C638058681963191909%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=KNOWTnrkAX9%2BUpKv6TeMKg8r8fOTznItXrTMurIf5MU%3D&reserved=0>, or unsubscribe<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAXZVEF6GNOP7WH6QNBN7ENTWLZERDANCNFSM6AAAAAARCUWO3Q&data=05%7C01%7Cjing.wu2%40nih.gov%7C8872ab13cfb64bb4180808dad6fd9af9%7C14b77578977342d58507251ca2dc2b06%7C0%7C0%7C638058681963191909%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=l4uHJZE%2FGYDmCaH3ZNq86ts3VBvrnRmirR1jd1EboU0%3D&reserved=0>.
You are receiving this because you were mentioned.Message ID: ***@***.***>
CAUTION: This email originated from outside of the organization. Do not click links or open attachments unless you recognize the sender and are confident the content is safe.

**Comment by jeannewu** [comment]
@StephanieWeinstein I have updated the tables and sent to you referred to the mock-up file you mentioned. Please check the tables and let me know if anything is needed. Thanks a lot.

**Comment by HopkinsDC** [comment]
The annotated metrics document (12/12) below includes comments, corrections, and edits to be made.
[biospecimen_metrics_baseline_participants_Prod_Clincal_Research_12122022_test.pdf](https://github.com/Analyticsphere/metricsReportsRequests/files/10272164/biospecimen_metrics_baseline_participants_Prod_Clincal_Research_12122022_test.pdf)

**Comment by HopkinsDC** [comment]
@KELSEYDOWLING7 Hi Kelsey. Michelle is still reviewing the biospecimen metrics report from 2/13 (https://nih.app.box.com/file/1139318861682) for any other edits that may need to be made to the report overall. When she is done, I will add a PDF of the report with our comments to this issue. Just as a preface, the report looked really good overall!

In the meantime, I will also be adding GitHub issues for additional metrics tables we want to be added to the report (they have been on hold until the metrics report was in a better place). You can start working on adding the new tables now, or you can wait until you get the PDF with our last round of comments and work on everything together. It is up to you. 

The biospecimen metrics report for this week (2/21) can be run as is.

Let me know if you have any questions or concerns.

**Comment by HopkinsDC** [comment]
@KELSEYDOWLING7 I'm adding the metrics report with our additional edits/comments from @brotzmanmj 's Friday email to keep all questions and responses together moving forward. Let us know if you have any questions or want to set up a Teams meeting to discuss anything. Thanks! 

[EDIT COMMENTS_Biospecimen-Weekly-Metrics-RMD_02_13_23.pdf](https://github.com/Analyticsphere/metricsReportsRequests/files/10840098/EDIT.COMMENTS_Biospecimen-Weekly-Metrics-RMD_02_13_23.pdf)

**Comment by jeannewu** [comment]
Hi, @HopkinsDC, the outliers of the research collection was defined before by the biospecimen team as the time greater than 24 hrs from the check-in to check-out: time gap between (d_331584571_d_266600170_d_343048998 and d_331584571_d_266600170_d_840048338). But now there is no outlier defined for the clinical collection, yet. And the NA in the Table20, is the participant (Connect_ID: 2927684519 from MFH) had his survey submission time (d_222161762) before the checkin time (d_331584571_d_266600170_d_840048338), which the time between survey submission to collection is categorized into "0 hrs to 3 hrs","> 3 hrs to 12 hrs","> 12 hrs to 24 hrs","> 24 hrs to 48 hrs","> 48 hrs to 72 hrs","greater than 72hrs (3days)". And for the clinical collection, the Table 21, the time from survey submission to check-in time  is defined as the survey submission time to the clinical collection time (the earlier collection time between urine and blood), which is categorized as the different levels (shown above). In this way, the NA in the Table 21, is the ones without their survey completion time (d_764863765). Hope my explanation would make sense.

**Comment by HopkinsDC** [comment]
@jeannewu Thank you for this explanation, Jing.

**Comment by KELSEYDOWLING7** [comment]
@HopkinsDC  For Table 15 I'm having issues putting a space between the sections (Site and tube type) as well as converting from column percentage to row percentage as the code is right now. What I can do more easily is split Table 15 into 15a by site and 15b by tube type, and have the row percentages. Please let me know your preference

**Comment by HopkinsDC** [comment]
@KELSEYDOWLING7 Splitting into two tables is a good idea. It'll honestly be easier to understand to data that way too. Thanks!

**Comment by KELSEYDOWLING7** [comment]
@HopkinsDC Great! Also can you clarify the row and column totals you want for table 6? The rows have both frequency and percent. I would understand column totals for frequency and for percent, but not sure what the row total would be. Thanks

**Comment by HopkinsDC** [comment]
@KELSEYDOWLING7 That comment is a mistake, sorry. We just need the column total for the count and the percent columns. 

Also, for Tables 6.0-6.9, can the denominator be changed from verified participants to verified participants who has had a baseline biospecimen appointment (**BioRec_CollectFinal_v1r0**  = Yes)?

**Comment by KELSEYDOWLING7** [comment]
@HopkinsDC  Ok that makes more sense. And that variable is yes for every participant thus far but I can add the filter if you think that may change

**Comment by HopkinsDC** [comment]
@KELSEYDOWLING7 If you can filter out any verified participants with **BioRec_CollectFinal_v1r0** = Null, that'll work.

**Comment by brotzmanmj** [comment]
This needs some clarification.... the variable **BioRec_CollectFinal_v1r0** is at the specimen level, not the participant level. We want the entire biospecimen metrics report to exclude any specimens that have BioRec_CollectFinal_v1r0 = Null. That signifies specimens that are not yet completely entered at the time the data were extracted to BQ1, or more likely, are specimens that were started to be entered but not finalized because they were entered in error and therefore should not be counted in the metrics. For metrics that are run at the participant level, if the only baseline sample they have was not finalized (ioRec_CollectFinal_v1r0 = Null for the sample) then we want it to not count as a sample collection at all. Often, those participants will have another sample that was entered and finalized so that one will count. I know this is a little confusing, so happy to discuss if that helps.

**Comment by KELSEYDOWLING7** [comment]
@HopkinsDC @brotzmanmj  Outside of adding the column totals of table 5 and row totals of tables 6.0-6.9 (because those will require me to recode the table- will take some time) all other requests I believe are satisfied in this updated report below. Please let me know what you think!
[Weekly-Biospecimen-Metrics-RMD_formatted.pdf](https://github.com/Analyticsphere/metricsReportsRequests/files/10876143/Weekly-Biospecimen-Metrics-RMD_formatted.pdf)

**Comment by HopkinsDC** [comment]
@KELSEYDOWLING7 Everything looks pretty good. Can you generate the metrics report today with the updates so I can review it with the most up-to-date data?

**Comment by KELSEYDOWLING7** [comment]
@HopkinsDC  Yes! The report is up in the March folder of the Biospecimen Weekly Metrics report

**Comment by HopkinsDC** [comment]
@KELSEYDOWLING7 Awesome, Thanks!

**Comment by HopkinsDC** [comment]
@KELSEYDOWLING7 I've reviewed today's metrics report (3/6). Please see the following comments.

- **Table 6**: Make "Based on data entered into Connect Biospecimen Dashboard." a footnote and remove it from the title.

-**Table20**: Change title to "Completion Time of Submitted Baseline Research Biospecimen Surveys from Time of Visit Check-In

-**Table21**: Change title to "Completion Time of Submitted Baseline Clinical Biospecimen Surveys from Time of Collection"

- **Table 22**: Remove the "Outlier" column. Exclude all collections with a visit length less than 8.0 minutes and more than 500.0 minutes for all sites. 

Everything else looks great!

**Comment by brotzmanmj** [comment]
HI @HopkinsDC can you also convey the change requested by the biospecimen team to tables 20 and 21 to change the denominator? Will also need to change the title from what is above. Thanks.

**Comment by HopkinsDC** [comment]
@KELSEYDOWLING7 Hi Kelsey, for tables 20 and 21, please disregard the title name changes and make the following edits:

- The denominator for table 20 needs to be changed to all baseline research biospecimen surveys. 
- The denominator for table 21 needs to be changed to all baseline clinical biospecimen surveys. 
- Rename the "Missing Time" column to "Not Submitted". With the change in the denominators, this column should include all surveys that have not been submitted (Not started + Started)

**Comment by brotzmanmj** [comment]
One clarification on the denominator: 
The denominator for table 20 needs to be changed to all participants with a baseline research biospecimen collection visit.
The denominator for table 21 needs to be changed to all participants with a baseline clinical biospecimen collection of blood or urine.

Thanks.

**Comment by KELSEYDOWLING7** [comment]
@brotzmanmj  Hi Michelle, do you know the variable names for those last two denominator requirements?

**Comment by brotzmanmj** [comment]
Hi @KELSEYDOWLING7
For table 20 you can use anyone who has an existing value of yes or no (not null) for visit check-in CID 135591601 (BioChk_Complete_v1r0). To explain, this variable is a toggle... it is null for all participants initially, is set to 1 when they are checked in for their baseline research visit, and is toggled to 0 when they are checked out at the end of their baseline research visit. The research survey triggers to people upon visit check in, which is why we want to use that as the denominator for this metric.

For table 21, you can use CID 156605577 (BioClin_AnyBldUrineRec_v1r0) as nested under baseline

**Comment by KELSEYDOWLING7** [comment]
It looks like Jing's original code already filters out data where BioChk_Complete_v1r0 is null and BioClin_AnyBldUrineRec_v1r0 is not null. So those denominators should already be correct. All other requested changes have been updated. 
[Weekly-Biospecimen-Metrics-RMD.pdf](https://github.com/Analyticsphere/metricsReportsRequests/files/10913376/Weekly-Biospecimen-Metrics-RMD.pdf)

**Comment by HopkinsDC** [comment]
@KELSEYDOWLING7 Please see my notes below.

- "Table 16" is missing; I think everything after Table 15b needs to be renumbered.
- **Table 20**: Rename the "NA's" row to "Not Submitted", and rename the "Not Submitted" row to "Missing Time".
- **Table 22**: Add the following footnote: Collection visits with a length of less than 8 minutes and greater than 5000 minutes are considered outliers and are excluded.

@brotzmanmj Do you think it would be beneficial to add a column to Table 22 stating the percentage of collection visits? (e.g., If HP has 600 total collection visits, but only 580 are included in the table, that would be 96.7% of the total number of collection visits).

**Comment by KELSEYDOWLING7** [comment]
@HopkinsDC Hi, Table 16 had a note on it to have the table removed. But I can rename the other tables accordingly. 

I'm a little confused on the Missing Time vs Not Submitted row request. You had asked for it to be changed to Not Submitted before. Should only table 20 have Missing Time and only Table 21 have Not Submitted?

For table 22 did you mean 500 minutes, like listed above? Or should that be 5,000?

**Comment by HopkinsDC** [comment]
@KELSEYDOWLING7 Hi Kelsey, I'm so sorry for the confusion. 

Yes, please renumber the other tables. I'd forgotten that table 16 was removed.

So far, only Table 20 has had 1 NA survey; This should be Missing Time. 

The update in [Michelle's comment](https://github.com/Analyticsphere/metricsReportsRequests/issues/8#issuecomment-1458238499) is the surveys that are Not Submitted. In Table 20, it's 261, and in Table 21, it's 17. (Let me know if this makes sense)

For Table 22, yes, I meant 500 minutes, not 5000. (It's been a rough morning haha)

**Comment by KELSEYDOWLING7** [comment]
@HopkinsDC Lol I understand. So I can reorder the tables and I see what you mean for Tables 20 and 21.


@brotzmanmj  here is that univariate visualization for now by site, below, and I'll work on the descriptive statistic
[Biospecimen-Issue-18.pdf](https://github.com/Analyticsphere/metricsReportsRequests/files/10922130/Biospecimen-Issue-18.pdf)

**Comment by KELSEYDOWLING7** [comment]
@brotzmanmj Here's an update of Table 22 with outliers for more information. Please let me know if you need something different 


![Table 22 with outliers](https://user-images.githubusercontent.com/101136647/223760246-4808a7d4-6b43-4718-a1bf-40b41c1bcf4f.PNG)

**Comment by KELSEYDOWLING7** [comment]
@HopkinsDC  Here's the full updated report with these new requests 
[Weekly-Biospecimen-Metrics-RMD.pdf](https://github.com/Analyticsphere/metricsReportsRequests/files/10923120/Weekly-Biospecimen-Metrics-RMD.pdf)

**Comment by brotzmanmj** [comment]
@KELSEYDOWLING7 maybe there is another way to get an this without the artificial definition of outliers you have in that table now. Perhaps if you combined the outlier and no outliers groups and then ran it? We might need more information though. I suggest we discuss with a quick chat.

**Comment by KELSEYDOWLING7** [comment]
@brotzmanmj  Me and Domonique have a meeting at 2:30 today to talk about issue #19. Does that time work for you?

**Comment by HopkinsDC** [comment]
@KELSEYDOWLING7 Hi Kelsey, please see the file for our comments

[EDITS 03092023_Weekly-Biospecimen-Metrics-RMD.pdf](https://github.com/Analyticsphere/metricsReportsRequests/files/10932868/EDITS.03092023_Weekly-Biospecimen-Metrics-RMD.pdf)

**Comment by KELSEYDOWLING7** [comment]
@HopkinsDC  Hi Domonique, would something like this work for Table 8? It's really hard to code row totals; it's easier to stay with column totals but switch the sites to the columns and tubes to the rows if that's acceptable
![Table 8 Attempt](https://user-images.githubusercontent.com/101136647/225352215-4d34dd14-0a19-4448-8516-f56e8bf932e9.PNG)

**Comment by KELSEYDOWLING7** [comment]
@HopkinsDC  Hi Domonique, nearly all requests have been completed, outside of converting Table 5 to column percentages and stratifying figures 3-5 by location as opposed to site. Those are proving difficult and I am still working on them. Please let me know how everything else looks, and feel free to let me know of additional requests to work on.


[Weekly-Biospecimen-Metrics-RMD.pdf](https://github.com/Analyticsphere/metricsReportsRequests/files/11018170/Weekly-Biospecimen-Metrics-RMD.pdf)

**Comment by KELSEYDOWLING7** [comment]
I'm not sure the reasoning, but this was the case for all the locations. The graphs are exactly the same regardless of the locations; there's just the same graph as it would be if I just ran it for each site. Is there any other concept ID I could use for the locations?

**Comment by brotzmanmj** [comment]
Good question. Which Concept ID are you using?

**Comment by HopkinsDC** [comment]
@KELSEYDOWLING7 Only 3 comments in the file below (in addition to the fixing the graphs above).

[COMMENTS 03202023 Weekly-Biospecimen-Metrics-RMD.pdf](https://github.com/Analyticsphere/metricsReportsRequests/files/11022872/COMMENTS.03202023.Weekly-Biospecimen-Metrics-RMD.pdf)

**Comment by KELSEYDOWLING7** [comment]
@HopkinsDC  Good morning, please see attached with all requests completed.

 I was able to restructure the collection variable to stratify it by location. Table 21 looks odd now without the 500 minute limit, but that can easily be changed again. 

[Weekly-Biospecimen-Metrics-RMD.pdf](https://github.com/Analyticsphere/metricsReportsRequests/files/11029286/Weekly-Biospecimen-Metrics-RMD.pdf)

**Comment by KELSEYDOWLING7** [comment]
Updated with row percentages on Table 5
[Weekly-Biospecimen-Metrics-RMD.pdf](https://github.com/Analyticsphere/metricsReportsRequests/files/11112652/Weekly-Biospecimen-Metrics-RMD.pdf)

**Comment by HopkinsDC** [comment]
@KELSEYDOWLING7 Hi Kelsey, we have another round of comments for the metrics report below. We want to start sharing this report with the sites soon, so many of the comments will be spelling corrections, capitalizations, and title adjustments. 

Let me know if you have any questions.

[COMMENTS_Weekly-Biospecimen-Metrics-RMD_03_27_23.pdf](https://github.com/Analyticsphere/metricsReportsRequests/files/11171128/COMMENTS_Weekly-Biospecimen-Metrics-RMD_03_27_23.pdf)

**Comment by KELSEYDOWLING7** [comment]
@HopkinsDC Hi Domonique, I confirmed that the footnote on Table 6 is correct. 

Can you clarify the note for Table 8 that says "...Baseline Clinical Collections..."? 

Also for Table 17, I will either need to do a separate table per site for the percentage to reflect status by site, or have one table with the cumulative percent of all Not Started, All Started, and all Submitted. Please let me know what you prefer

**Comment by HopkinsDC** [comment]
@KELSEYDOWLING7 

Thank you for confirming the footnote in Table 6.

For Table 8, update the title to say "Baseline _Clinical_ Collections" instead of " Baseline _Clinic_ Collections"

For table 17, keep table 17 as it (cumulative) and make a separate table for each site. Number them 17.1, 17.2, etc. This can also be applied to Table 19 as well.

**Comment by KELSEYDOWLING7** [comment]
@HopkinsDC Do you want Figure 9 cut off so that it only shows from February 2023 on?

**Comment by HopkinsDC** [comment]
@KELSEYDOWLING7 For Figures 8 through 11, exclude collections before 1/30/23.

**Comment by KELSEYDOWLING7** [comment]
@HopkinsDC Ok thanks for the clarification! For Plots 8-11 Michelle had some concerns on the amount of collections in any given week but the numbers seem to add up. When I compare the plots with the total number of (any) specimen donated in table 1 to those plots, those figures match

**Comment by HopkinsDC** [comment]
@KELSEYDOWLING7 The plots look correct to me as well. I'll bring this up with her next week. Once the collections before 1/30/23 are excluded, the plots will look better overall, so just make that change, and we'll review it again.

**Comment by HopkinsDC** [comment]
@KELSEYDOWLING7 Also, if you can make the dates on the x-axis the Monday of each week, if possible, that might help as well.

**Comment by KELSEYDOWLING7** [comment]
@HopkinsDC  Ok I'll see what I can do about the dates. The only edit I have left is tables 15a&15b not totaling to Table 13. Is it possible that a tube could be marked as not collected with a reason, and that the participant could return before weeks end or later that day to re-donate?

**Comment by HopkinsDC** [comment]
@KELSEYDOWLING7 The "total" column in Table 15b matches the "total" row in Table 13, which checks out.

The "total" column in Table 15a doesn't match the "total" column in Table 13 because Table 13 does not include urine and mouthwash tubes not collected. Table 13 is just blood tubes not collected. 

You can leave it as is, and I'll point this out to Michelle next week. Thanks!

**Comment by KELSEYDOWLING7** [comment]
Great! In that case, please see the updated report below
[Weekly-Biospecimen-Metrics-RMD.pdf](https://github.com/Analyticsphere/metricsReportsRequests/files/11180232/Weekly-Biospecimen-Metrics-RMD.pdf)

**Comment by StephanieWeinstein** [comment]
Hi Kelsey, 
This is fantastic, thank you for getting this updated so quickly. Some of the new tables are very illuminating! - but unfortunately not in a good way :-(  

Did you double check the y-axis on some of the plots?  For example, on figure 2, which is all sites combined, the y-axis goes up to 125 collections per week, but figure 3 which is Henry Ford only, goes over 3000 collections per week, which can't be right.  Same for Fig 4 and 5.

Also, I feel like something is weird on figure 5/Marshfield (and possibly similar issues on some other plots). The red and green lines look to have the exact the same pattern (although green is always higher than red). This seems strange.  It makes sense that they both have low collections the week of Thanksgiving, but I would not expect them to track so identically on the other weeks.  Also we had a black out for the last two weeks of December so there should not have been any collections those weeks.

Thank you!!

**Comment by StephanieWeinstein** [comment]
@brotzmanmj  and @HopkinsDC, on the figures I think the counts should be 1 per participant if anything is donated. Do you agree?

**Comment by brotzmanmj** [comment]
agreed, the collection counts should be 1 per participant in this instance.

**Comment by KELSEYDOWLING7** [comment]
@brotzmanmj  Ok so these plots should essentially match the counts in Table 1, correct?

**Comment by KELSEYDOWLING7** [comment]
Ok, these look correct now.

[Weekly-Biospecimen-Metrics-RMD.pdf](https://github.com/Analyticsphere/metricsReportsRequests/files/11192782/Weekly-Biospecimen-Metrics-RMD.pdf)


 I'm having some issues reincorporating the locations of UC, Henry Ford and Marshfield. So for now I'll keep those plots to one per site and work on the additional stratification over the week.

**Comment by StephanieWeinstein** [comment]
Thank you!

**Comment by HopkinsDC** [comment]
@KELSEYDOWLING7 Hi Kelsey, we have a handful of edits for the report. I've added them to the most recent metrics report from [your comment above](https://github.com/Analyticsphere/metricsReportsRequests/issues/8#issuecomment-1502141942).

Let me know if you have any questions.

**Comment by KELSEYDOWLING7** [comment]
@HopkinsDC  All set! Let me know how this looks
[Weekly-Biospecimen-Metrics-RMD.pdf](https://github.com/Analyticsphere/metricsReportsRequests/files/11225049/Weekly-Biospecimen-Metrics-RMD.pdf)

**Comment by KELSEYDOWLING7** [comment]
Updated with #23 
[Weekly-Biospecimen-Metrics-RMD.pdf](https://github.com/Analyticsphere/metricsReportsRequests/files/11225913/Weekly-Biospecimen-Metrics-RMD.pdf)

**Comment by brotzmanmj** [comment]
Hi, we aim to start sharing this report out to the sites next week, based on data extracted on Monday 4/17. I'd like to do a quick review to compare against the comments to make sure everything was addressed but it's a bit of a moving target. Can you tell me which version I should review of the metrics that will be closest to what we release on Monday, and which document contains the comments that I can compare against? This should include the comments I gave right before I left on on PTO the middle of last week.

**Comment by HopkinsDC** [comment]
@brotzmanmj 

Report version that's the most up to date: https://github.com/Analyticsphere/metricsReportsRequests/files/11225913/Weekly-Biospecimen-Metrics-RMD.pdf

Report with comments for comparison: https://github.com/Analyticsphere/metricsReportsRequests/files/11171128/COMMENTS_Weekly-Biospecimen-Metrics-RMD_03_27_23.pdf

**Comment by KELSEYDOWLING7** [comment]
I am still working to reduce the space between "Tables" and the first table, reduce the font size of the footnotes, and remove the odd spacing of the ACD tube column in Table 9. But other than those, here's all other requests met thus far. 
[Weekly-Biospecimen-Metrics-RMD.pdf](https://github.com/Analyticsphere/metricsReportsRequests/files/11235946/Weekly-Biospecimen-Metrics-RMD.pdf)

**Comment by HopkinsDC** [comment]
@KELSEYDOWLING7 (Reminder from bio QC meeting last week) 
For Tables 15a and 15b, please check/confirm that the denominator includes all tubes not collected. If no reason was selected, add a column titled "No Reason Selected" with the count and percent.

**Comment by KELSEYDOWLING7** [comment]
@HopkinsDC  Good morning, I have verified that those figures are correct. That will be the figure we reference when we move forward with the QC checks too

**Comment by HopkinsDC** [comment]
@KELSEYDOWLING7 Thanks, Kelsey.

Also, one small change to the biospecimen metrics report: For table 5 (Baseline Biospecimen Collection by Collection Setting), please change to **column** totals/percents.

**Comment by KELSEYDOWLING7** [comment]
@HopkinsDC  All set, please see attached
[Weekly-Biospecimen-Metrics-RMD.pdf](https://github.com/Analyticsphere/metricsReportsRequests/files/11314024/Weekly-Biospecimen-Metrics-RMD.pdf)

**Comment by StephanieWeinstein** [comment]
Thank you Kelsey!

**Comment by HopkinsDC** [comment]
@KELSEYDOWLING7 Hi Kelsey, this issue can be considered complete. Any additional tables or figures added to the biospecimen metrics will get their own issue moving forward. This issue thread is way too long haha.
