### ISSUE TITLE
Bio Weekly - Discrepancy Between Figures 6-15 & Weekly Logs

### ISSUE THREAD

**Issue by HopkinsDC** [Analyticsphere/metricsReportsRequests#80]
As a stand-alone issue from #59, Per discussion on email with Michelle, please update Figures 6 through 15 on the Biospecimen Weekly Metrics Report to include weekly collection counts through the latest 'complete' week corresponding to the weekly log.

**Requestor(s):** Michelle

**Table or Figure title:** Figures 6-15

**Metrics to be updated or created:** Update figures

**Variables needed (include variable name and Concept ID):** N/A

**Specify numerator and denominator by variable name where applicable:** N/A

**Mock-up table if applicable:** N/A

**Notes:** N/A

**Approved by:** Domonique

**Comment by KELSEYDOWLING7** [comment]
@HopkinsDC  @brotzmanmj  Please let me know how these look. Jake and I are meeting shortly to go over the automation changes for Monday.

It looks as though we were just off by a week, so that timing has now been adjusted so the right counts go with the right weeks.

The only plot that will be off slightly is the All sites. Jing and I compared her code between the Operations report (logs) and the Biospecimen Report; the research sites and the clinical sites have to be calculated differently, and the biospecimen report and the operations report have different data sets (as the biospecimen report merges in the biospecimen table). But the sites plots should match the logs. 


![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/a673a488-f3ad-42f5-962a-6026afb670ac)
![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/63ae85bf-088b-4eba-ab81-f551ecf9a1ef)
![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/619146b3-2a79-42d0-8e34-1daddfe7da6e)
![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/f02ec2d8-39b2-4175-9eab-5e36fb74109a)
![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/d8f5b727-aad0-4a55-91f8-9ff53d36c6cb)
![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/af03d3c6-4c3b-4530-afb2-325782384af1)
![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/07f94e48-a926-475f-bfe5-4720da160041)
![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/a3f67bf4-3d35-4800-a8c5-f9b153dc96f0)
![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/8eab3317-ce7f-4f3a-b630-92b391e347a9)
![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/6a4edf51-782a-4482-b117-a97d5a7270be)
![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/0a18b68d-7835-4a3e-a3db-b75950cbbb00)
![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/b576f424-a523-4e6a-8c0f-69bd8acd2d50)
![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/dc47d7f7-f853-4a28-8a23-1aa94a66eda6)
![image](https://github.com/Analyticsphere/metricsReportsRequests/assets/101136647/48860dfa-b1b0-4dd4-adcb-8baad6b7dee3)

**Comment by HopkinsDC** [comment]
@KELSEYDOWLING7 I've compared the updated plots to the weekly logs and they are now in sync. Thank you for making these adjustments. 

This can be included in the next scheduled metrics automation update.

**Comment by HopkinsDC** [comment]
Update successfully implemented in 11/6 weekly biospecimen metrics report.
